include:
  - postgres.yaml
  - redis.yaml
  - nginx.yaml
  - keycloak.yaml

services:
  coredns:
    container_name: coredns_container
    hostname: coredns.docker.space
    dns:
      - 172.28.22.8
    image: coredns/coredns:1.12.1
    restart: always
    volumes:
      - ./coredns/conf:/conf
    ports:
      - "53:53"
    networks:
      fzkc-net01:
        ipv4_address: 172.28.22.8
    entrypoint: /coredns -conf /conf/Corefile


networks:
  fzkc-net01:
    ipam:
      driver: default
      config:
        - subnet: 172.28.22.0/24
          gateway: 172.28.22.1

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./postgres/var/lib/postgresql/data
      o: bind

  keycloak_opt:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak/opt
      o: bind

  nginx_etc:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/etc/nginx
      o: bind

  nginx_var:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/var
      o: bind
  