include:
  - postgres.yaml
  - redis.yaml
  - nginx.yaml
  - keycloak.yaml
  - coredns.yaml
  
networks:
  fzkc-net01:
    ipam:
      driver: default
      config:
        - subnet: ${FZKC_NETWORK}
          gateway: ${FZKC_NETWORK_GATEWAY}

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./postgres/var/lib/postgresql/data
      o: bind

  keycloak-conf:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak/opt/keycloak/conf
      o: bind

  keycloak-providers:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak/opt/keycloak/providers
      o: bind

  keycloak-themes:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak/opt/keycloak/themes
      o: bind

  nginx-etc:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/etc/nginx
      o: bind

  nginx-var-log:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/var/log
      o: bind

  nginx-var-www:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/var/www
      o: bind
  