# https://stackoverflow.com/questions/36035595/communicating-between-docker-containers-in-different-networks-on-the-same-host

#
# iptables -I DOCKER-USER -i <vnic1> -o <vnic2> -j ACCEPT
# iptables -I DOCKER-USER -i <vnic2> -o <vnic1> -j ACCEPT
#

include:
  - postgres.yaml
  - redis.yaml
  - memcached.yaml
  - nginx.yaml
  - keycloak.yaml
  - coredns.yaml
  - mongodb.yaml
  - opensearch.yaml
  - graylog.yaml
  
networks:
  fzkc-net01:
    ipam:
      driver: default
      config:
        - subnet: ${FZKC_NETWORK}
          gateway: ${FZKC_NETWORK_GATEWAY_IP}

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./postgres/var/lib/postgresql/data
      o: bind

  keycloak-conf:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak/opt/keycloak/conf
      o: bind

  keycloak-providers:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak/opt/keycloak/providers
      o: bind

  keycloak-themes:
    driver: local
    driver_opts:
      type: none
      device: ./keycloak/opt/keycloak/themes
      o: bind

  nginx-etc:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/etc/nginx
      o: bind

  nginx-var-log:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/var/log
      o: bind

  nginx-var-www:
    driver: local
    driver_opts:
      type: none
      device: ./nginx/var/www
      o: bind

  redis-conf:
    driver: local
    driver_opts:
      type: none
      device: ./redis/conf
      o: bind
  
  memcached-conf:
    driver: local
    driver_opts:
      type: none
      device: ./memcached/conf
      o: bind

  mongodb-data:
    driver: local
    driver_opts:
      type: none
      device: ./mongodb/mongo_data
      o: bind

  mongodb-config:
    driver: local
    driver_opts:
      type: none
      device: ./mongodb/mongo_config
      o: bind

  opensearch-data:
    driver: local
    driver_opts:
      type: none
      device: ./opensearch/os_data
      o: bind

  graylog-journal:
    driver: local
    driver_opts:
      type: none
      device: ./graylog/graylog_journal
      o: bind
  
