services:
  coredns:
    cap_add:
      - NET_ADMIN
    build:
      context: ./../__dfiles/coredns
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-coredns-container
    env_file:
      - ./.env
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      FZKC_PROJECT_NAME: ${FZKC_PROJECT_NAME}
    hostname: coredns.${FZKC_PROJECT_NAME}.space
    dns:
      - 127.0.0.1
    restart: always
    volumes:
      - ./coredns/conf:/conf
    ports:
      - "${FZKC_EXPOSED_PORT_DNS}:${FZKC_EXPOSED_PORT_DNS}"
    networks:
      fzkc-net01:
        ipv4_address: ${FZKC_NETWORK_DNS_IP}