services:
  keycloak:
    build:
      context: ./../__dfiles/keycloak
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-keycloak-container
    environment:
      KC_HOSTNAME: keycloak.${FZKC_PROJECT_NAME}.space
      KC_HTTP_ENABLED: "true"
      KC_HTTP_HOST: "0.0.0.0"
      KC_HTTP_PORT: 8880
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: postgres.${FZKC_PROJECT_NAME}.space
      KC_DB_URL_PORT: ${FZKC_EXPOSED_PORT_POSTGRES}
      KC_DB_URL_DATABASE: keycloak
    hostname: keycloak.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    volumes:
      - keycloak-conf:/opt/keycloak/conf
      - keycloak-providers:/opt/keycloak/providers
      - keycloak-providers:/opt/keycloak/themes
    ports:
      - "${FZKC_EXPOSED_PORT_KEYCLOAK}:8880"
      - "${FZKC_EXPOSED_PORT_KEYCLOAK_MANAGEMENT}:9000"
    depends_on:
      - postgres
    networks:
      - fzkc-net01
    command: ["start", "--optimized"]
