services:
  keycloak:
    build:
      context: ./../__dfiles/keycloak
      dockerfile: Dockerfile
    container_name: keycloak_container
    environment:
      KC_HOSTNAME: keycloak.docker.space
      KC_HTTP_ENABLED: "true"
      KC_HTTP_HOST: "0.0.0.0"
      KC_HTTP_PORT: 8880
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: postgres.docker.space
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
    hostname: keycloak.docker.space
    dns:
      - 172.28.22.8
    restart: always
    volumes:
      - keycloak_opt:/opt/keycloak
    ports:
      - "8880:8880"
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      fzkc_net01:
        ipv4_address: 172.28.22.12
    command: ["start", "--optimized"]
