services:
  memcached:
    cap_add:
      - NET_ADMIN
    build:
      context: ./../__dfiles/memcached
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-memcached-container
    env_file:
      - ./.env
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      FZKC_PROJECT_NAME: ${FZKC_PROJECT_NAME}
      COLUMNS: ${COLUMNS}
      LINES: ${LINES}
      TERM: ${TERM}
    hostname: memcached.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    volumes:
      - memcached-conf:/mnt
    ports:
      - "${FZKC_EXPOSED_PORT_MEMCACHED}:${FZKC_EXPOSED_PORT_MEMCACHED}"
    networks:
      - fzkc-net01
