services:
  nginx:
    cap_add:
      - NET_ADMIN
    build:
      context: ./../__dfiles/nginx/
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-nginx-container
    env_file:
      - ./.env
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      FZKC_PROJECT_NAME: ${FZKC_PROJECT_NAME}
      FZKC_EXPOSED_PORT_NGINX_HTTP: ${FZKC_EXPOSED_PORT_NGINX_HTTP}
      FZKC_EXPOSED_PORT_NGINX_HTTPS: ${FZKC_EXPOSED_PORT_NGINX_HTTPS}
      #NGINX_ENTRYPOINT_QUIET_LOGS: 1
      #DNS_RECORD: "969b086a94ec02debe10ae16232f2ded"
      #DNS_RECORD_NAME: "test.fuzzy-net.it"
    hostname: nginx.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    volumes:
      - nginx-etc:/etc/nginx
      - nginx-var-log:/var/log
      - nginx-var-www:/var/www
    ports:
      - "${FZKC_EXPOSED_PORT_NGINX_HTTP}:${FZKC_EXPOSED_PORT_NGINX_HTTP}"
      - "${FZKC_EXPOSED_PORT_NGINX_HTTPS}:${FZKC_EXPOSED_PORT_NGINX_HTTPS}"
    networks:
      - fzkc-net01

  