services:
  nginx:
    build:
      context: ./../__dfiles/nginx/
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-nginx-container
    #environment:
      #NGINX_ENTRYPOINT_QUIET_LOGS: 1
      #DNS_RECORD: "969b086a94ec02debe10ae16232f2ded"
      #DNS_RECORD_NAME: "test.fuzzy-net.it"
    hostname: nginx.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    volumes:
      - ./nginx/docker-entrypoint.d:/docker-entrypoint.d
      - nginx-etc:/etc/nginx
      - nginx-var-log:/var/log
      - nginx-var-www:/var/www
      #- ./../../laravels/backend/public:/backend
    ports:
      - "${FZKC_EXPOSED_PORT_NGINX_HTTP}:80"
      - "${FZKC_EXPOSED_PORT_NGINX_HTTPS}:443"
    depends_on:
      - postgres
    networks:
      - fzkc-net01

  