services:
  postgres:
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: C.UTF-8
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale-provider=icu --icu-locale=und'
    hostname: postgres.docker.space
    dns:
      - 172.28.22.8
    image: postgres:17.2
    restart: always
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data     
    ports: 
      - "5432:5432"
    networks:
      fzkc_dev_net01:
        ipv4_address: 172.28.22.9
  