services:
  postgres:
    cap_add:
      - NET_ADMIN
    build:
      context: ./../__dfiles/postgres
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-postgres-container
    env_file:
      - ./.env
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      FZKC_PROJECT_NAME: ${FZKC_PROJECT_NAME}
      COLUMNS: ${COLUMNS}
      LINES: ${LINES}
      TERM: ${TERM}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: ${FZKC_EXPOSED_PORT_POSTGRES}
      PGDATA: /var/lib/postgresql/data/pgdata
      LANG: C.UTF-8
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale-provider=icu --icu-locale=und'
    hostname: postgres.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data     
    ports: 
      - "${FZKC_EXPOSED_PORT_POSTGRES}:${FZKC_EXPOSED_PORT_POSTGRES}"
    networks:
      - fzkc-net01
  