services:
  redis:
    build:
      context: ./../__dfiles/redis
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_redis_container
    hostname: redis.docker.space
    dns:
      - 172.28.22.8
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - postgres
    networks:
      fzkc-net01:
        ipv4_address: 172.28.22.10
