services:
  redis:
    cap_add:
      - NET_ADMIN
    build:
      context: ./../__dfiles/redis
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-redis-container
    env_file:
      - ./.env
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      FZKC_PROJECT_NAME: ${FZKC_PROJECT_NAME}
      COLUMNS: ${COLUMNS}
      LINES: ${LINES}
      TERM: ${TERM}
    hostname: redis.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    volumes:
      - redis-conf:/mnt
    ports:
      - "${FZKC_EXPOSED_PORT_REDIS}:${FZKC_EXPOSED_PORT_REDIS}"
    networks:
      - fzkc-net01
