services:
  redis:
    build:
      context: ./../__dfiles/redis
      dockerfile: Dockerfile
    container_name: ${FZKC_PROJECT_NAME}-redis-container
    hostname: redis.${FZKC_PROJECT_NAME}.space
    dns:
      - ${FZKC_NETWORK_DNS_IP}
    restart: always
    ports:
      - "${FZKC_EXPOSED_PORT_REDIS}:6379"
    depends_on:
      - postgres
    networks:
      - fzkc-net01
